### ISSUE TITLE
AnimationController.dispose() called more than once

### ISSUE THREAD

**Issue by hiddenMonster** [smokelaboratory/motion_widget#6]
Hi Sumeet,
How I do with this Exception please?

StackTrace:
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
AnimationController.dispose() called more than once.

A given AnimationController cannot be disposed more than once.

The following AnimationController object was disposed multiple times: AnimationController#8f166(⏮ 0.000; paused; DISPOSED)
When the exception was thrown, this was the stack: 
#0      AnimationController.dispose.<anonymous closure> (package:flutter/src/animation/animation_controller.dart:755:9)
#1      AnimationController.dispose (package:flutter/src/animation/animation_controller.dart:766:6)
#2      _MotionState.dispose (package:motion_widget/motion_widget.dart:153:44)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4729:12)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

Thank you so much in advance!

**Comment by hiddenMonster** [comment]
Hi I solved the above exception by simply not using the Motion parameter **exitConfigurations** which is suggested in your package instructions, but not mandatory or required !!! I wish this will help other users :)
Your package is amazing!!!
Thank you
